# Site settings
title: Ifeoluwa Babatunde's Website
description: Ifeoluwa Babatunde's personal blog
# url: "ifeoluwababatunde.com"
permalink: pretty

# Sass
sass:
    sass_dir: _sass

# Navigation Bar
# navigation-header:
#   Home: /
#   Posts: /posts/
#   Categories: /Categories/
#   Projects: /projects/

# User settings
username: Ifeoluwa Babatunde
user_title: Data Scientist
email: ifebabatunde15@gmail.com

exclude: ['package.json', 'src' , 'node_modules']
